### ISSUE TITLE
Add cluster configuration for failover and dynamic settings

### ISSUE THREAD

**Issue by samuel-lindgren** [cadence-workflow/cadence-charts#14]
The official Cadence Helm Chart lacks configurations for failover mechanisms and dynamic cluster settings, which are important for high availability and resilience.

**Proposed Changes**

Add options to configure failover mechanisms and dynamic cluster settings.

**Comment by samuel-lindgren** [comment]
> Hi [@samuel-lindgren](https://github.com/samuel-lindgren) can you explain more in what do you mean with failover mechanisms? Do you have any example?
> 
> You mean health checks to check if the app/pod is alive/working?

Hi! I realize my comment was vague. By "failover mechanisms," I'm not referring to pod/app health checks. Instead, I'm talking about multi-cluster failover capabilities in Cadence.

This is what type of configuration that I'm referring to:

```
clusterGroupMetadata:
  clusterRedirectionPolicy:
    policy: "all-domain-apis-forwarding"
  failoverVersionIncrement: 10            # Version increment during failover events
  primaryClusterName: "active"            # Which cluster is primary
  currentClusterName: "active"            # The name of the current cluster
  clusterGroup:
    active:
      enabled: true
      initialFailoverVersion: 0
      rpcName: "cadence-frontend"
      rpcAddress: "cadence-frontend:7933"  
```
