### ISSUE TITLE
Running Cadence in EKS using Fargate

### ISSUE THREAD

**Issue by jmathew-grail** [cadence-workflow/cadence-charts#22]
Hello everyone! Thank you for the official charts to run Cadence. We recently starting using them to deploy cadence to Fargate based EKS. I'm using the latest version of cadence `v.1.2.17` to deploy `worker`, `frontend`, `matching`,`history`, and `web` as separate deployments. To test the deployment, I have a scanner workflow that I use to trigger a workflow and poll on its status. I haven't been able to get them to pass. Based on the error message in worker, `error reading server preface`, I'm assuming there is something wrong with my ringpop configuration. I'm looking for pointers from the cadence community on

* In the rings list, should I be seeing more than 2 members for each role?
* In the rings list, I only see most of the rpc ports listed, but in many of errors I see when I do other tests, I can see the grpc port being used with the unreachable message. Do I need to change `bootstrapMode` to `hosts` for grpc ports to be listed?
* In the parsed docker.yaml file, I can see both rpc and grpc port listed, but I don't see them when I do `cadence describe`. Is that a problem?
* Any sample ringpop configuration that uses the latest or close to latest version of cadence.
* Any debugging steps I can use to validate connectivity.

**Full error message**
```
{
  "level": "error",
  "ts": 1741790099.3651657,
  "logger": "scanner",
  "caller": "scanner/scanner.go:259",
  "msg": "Failed to start workflow",
  "workflowType": "cadence-sys-tl-scanner-workflow",
  "error": 'code:unavailable message:connection error: desc = "error reading server preface: EOF"',
  "stacktrace": "github.com/uber/cadence/service/worker/scanner.(*Scanner).startWorkflow\n\t/cadence/service/worker/scanner/scanner.go:259\ngithub.com/uber/cadence/service/worker/scanner.(*Scanner).startScanner.func1\n\t/cadence/service/worker/scanner/scanner.go:180\ngithub.com/uber/cadence/service/worker/workercommon.StartWorkflowWithRetry.func2\n\t/cadence/service/worker/workercommon/util.go:57\ngithub.com/uber/cadence/common/backoff.(*ThrottleRetry).Do\n\t/cadence/common/backoff/retry.go:172\ngithub.com/uber/cadence/service/worker/workercommon.StartWorkflowWithRetry\n\t/cadence/service/worker/workercommon/util.go:56",
}

```

**Ringpop Configuration**
```
            ringpop:
                name: cadence
                broadcastAddress: {{ default .Env.BROADCAST_ADDRESS "" }}
                bootstrapMode: {{ default .Env.RINGPOP_BOOTSTRAP_MODE "hosts" }}
                {{- if .Env.RINGPOP_SEEDS }}
                bootstrapHosts:
                {{- range $seed := (split .Env.RINGPOP_SEEDS ",") }}
                    - {{ . }}
                {{- end }}
                {{- else }}
                bootstrapHosts:
                    - {{ .Env.HOST_IP }}:{{ default .Env.FRONTEND_PORT "7933" }}
                    - {{ .Env.HOST_IP }}:{{ default .Env.HISTORY_PORT "7934" }}
                    - {{ .Env.HOST_IP }}:{{ default .Env.MATCHING_PORT "7935" }}
                    - {{ .Env.HOST_IP }}:{{ default .Env.WORKER_PORT "7939" }}
                {{- end }}
                maxJoinDuration: 30s

            services:
                frontend:
                    rpc:
                        port: {{ default .Env.FRONTEND_PORT "7933" }}
                        grpcPort: {{ default .Env.GRPC_FRONTEND_PORT "7833" }}
                        bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
                        {{- if .Env.FRONTEND_HTTP_PORT }}
                        http:
                            port: {{ .Env.FRONTEND_HTTP_PORT }}
                            procedures:
                            {{- range $seed := (split .Env.FRONTEND_HTTP_PROCEDURES ",") }}
                                - {{ . }}
                            {{- end }}
                        {{- end }}
                    {{- if .Env.STATSD_ENDPOINT }}
                    metrics:
                        statsd:
                            hostPort: {{ .Env.STATSD_ENDPOINT }}
                            prefix: {{ default .Env.STATSD_FRONTEND_PREFIX "cadence-frontend" }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT_0 }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_0 }}
                    {{- end }}

                matching:
                    rpc:
                        port: {{ default .Env.MATCHING_PORT "7935" }}
                        grpcPort: {{ default .Env.GRPC_MATCHING_PORT "7835" }}
                        bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
                    {{- if .Env.STATSD_ENDPOINT }}
                    metrics:
                        statsd:
                            hostPort: {{ .Env.STATSD_ENDPOINT }}
                            prefix: {{ default .Env.STATSD_MATCHING_PREFIX "cadence-matching" }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT_1 }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_1 }}
                    {{- end }}

                history:
                    rpc:
                        port: {{ default .Env.HISTORY_PORT "7934" }}
                        grpcPort: {{ default .Env.GRPC_HISTORY_PORT "7834" }}
                        bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
                    {{- if .Env.STATSD_ENDPOINT }}
                    metrics:
                        statsd:
                            hostPort: {{ .Env.STATSD_ENDPOINT }}
                            prefix: {{ default .Env.STATSD_HISTORY_PREFIX "cadence-history" }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT_2 }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_2 }}
                    {{- end }}

                worker:
                    rpc:
                        port: {{ default .Env.WORKER_PORT "7939" }}
                        grpcPort: {{ default .Env.GRPC_WORKER_PORT "7839" }}
                        bindOnIP: {{ default .Env.BIND_ON_IP "127.0.0.1" }}
                    {{- if .Env.STATSD_ENDPOINT }}
                    metrics:
                        statsd:
                            hostPort: {{ .Env.STATSD_ENDPOINT }}
                            prefix: {{ default .Env.STATSD_WORKER_PREFIX "cadence-worker" }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT }}
                    {{- else if .Env.PROMETHEUS_ENDPOINT_3 }}
                    metrics:
                        prometheus:
                            timerType: {{ default .Env.PROMETHEUS_TIMER_TYPE "histogram" }}
                            listenAddress: {{ .Env.PROMETHEUS_ENDPOINT_3 }}
                    {{- end }}

```

**Ringpop Status**
`cadence --address cadence-frontend:7933 admin cluster describe`

```
{
  "supportedClientVersions": {
    "goSdk": "1.7.0",
    "javaSdk": "1.5.0"
  },
  "membershipInfo": {
    "currentHost": {
      "Identity": "[REDACTED_IP]:7933"
    },
    "reachableMembers": [
      "[REDACTED_IP]:7933",
      "[REDACTED_IP]:7933", # I have two replicas running for each
      "[REDACTED_IP]:7934",
      "[REDACTED_IP]:7934",
      "[REDACTED_IP]:7935",
      "[REDACTED_IP]:7935",
      "[REDACTED_IP]:7939",
      "[REDACTED_IP]:7939"
    ],
    "rings": [
      {
        "role": "cadence-frontend",
        "memberCount": 2,
        "members": [
          {
            "Identity": "[REDACTED_IP]:7933" # Two replicas
          },
          {
            "Identity": "[REDACTED_IP]:7933"
          }
        ]
      },
      {
        "role": "cadence-history",
        "memberCount": 2,
        "members": [
          {
            "Identity": "[REDACTED_IP]:7934"
          },
          {
            "Identity": "[REDACTED_IP]:7934"
          }
        ]
      },
      {
        "role": "cadence-matching",
        "memberCount": 2,
        "members": [
          {
            "Identity": "[REDACTED_IP]:7935"
          },
          {
            "Identity": "[REDACTED_IP]:7935"
          }
        ]
      },
      {
        "role": "cadence-worker",
        "memberCount": 2,
        "members": [
          {
            "Identity": "[REDACTED_IP]:7939"
          },
          {
            "Identity": "[REDACTED_IP]:7939"
          }
        ]
      }
    ]
  },
  "persistenceInfo": {
    "historyStore": {
      "backend": "mysql"
    },
    "visibilityStore": {
      "backend": “mysql”,
      “features”: [
        {
          “key”: “advancedVisibilityEnabled”,
          “enabled”: false
       }
     ]
   }
}
```

**Docker.yaml file**
I got this from the container `cat config/docker.yaml`

```
ringpop:
    name: cadence
    broadcastAddress: [REDACTED_IP]
    bootstrapMode: dns
    bootstrapHosts:
        - [REDACTED_HOSTNAME]:7933
        - [REDACTED_HOSTNAME]:7833
        - [REDACTED_HOSTNAME]:7934
        - [REDACTED_HOSTNAME]:7834
        - [REDACTED_HOSTNAME]:7935
        - [REDACTED_HOSTNAME]:7835
        - [REDACTED_HOSTNAME]:7939
    maxJoinDuration: 30s

services:
    frontend:
        rpc:
            port: 7933
            grpcPort: 7833
            bindOnIP: 0.0.0.0
        metrics:
            prometheus:
                timerType: histogram
                listenAddress: 0.0.0.0:9100

    matching:
        rpc:
            port: 7935
            grpcPort: 7835
            bindOnIP: 0.0.0.0
        metrics:
            prometheus:
                timerType: histogram
                listenAddress: 0.0.0.0:9100

    history:
        rpc:
            port: 7934
            grpcPort: 7834
            bindOnIP: 0.0.0.0
        metrics:
            prometheus:
                timerType: histogram
                listenAddress: 0.0.0.0:9100

    worker:
        rpc:
            port: 7939
            grpcPort: 7839
            bindOnIP: 0.0.0.0
        metrics:
            prometheus:
                timerType: histogram
                listenAddress: 0.0.0.0:9100
```

**Comment by taylanisikdemir** [comment]
`bootstrapMode: dns` might be the issue because the list of hosts in the ringpop config are ip addresses. Change it to `bootstrapMode: hosts` and try again. 
Also double check if `broadcastAddress` is populated properly for each pod instance. 
If it still doesn't work please share the logs from containers.

**Comment by jmathew-grail** [comment]
Thank you for that point @taylanisikdemir. The following settings got things to work, which is exactly what you pointing to.

```
ringpop:
                name: cadence
                broadcastAddress: {{ default .Env.BROADCAST_ADDRESS "" }}
                bootstrapMode: {{ default .Env.RINGPOP_BOOTSTRAP_MODE "hosts" }}
```
