### ISSUE TITLE
Issue Prometheus Metrics Error in Cadence Helm Chart v1.3.1

### ISSUE THREAD

**Issue by CosminL-DEV** [cadence-workflow/cadence-charts#39]
When installing the Cadence Helm chart version 1.3.1, a continuous error appears in all Cadence components related to Prometheus metrics.

## Root Cause & Resolution Status

This issue is already resolved in the upstream repository: https://github.com/cadence-workflow/cadence/pull/6963

The fix will be published in version 1.3.2. I'm opening this issue to keep track of this problem in this repository and ensure awareness when that version is released.

### config_template.yaml
```yaml
# Log configuration
log:
  stdout: true
  level: info
  levelKey: level
  encoding: json

# Persistence configuration
persistence:
  numHistoryShards: 4
  defaultStore: "default"
  visibilityStore: "visibility"
  enablePersistenceLatencyHistogramMetrics: false

  # DataStores configuration
  datastores:
    # Default datastore
    default:
      nosql:
        pluginName: "cassandra"
        hosts: "cassandra-service.cadence.svc.cluster.local"
        keyspace: "cadence"
        user: "cassandra"
        password: {{ .Env.CASSANDRA_PASSWORD }}
        protoVersion: 4
        maxConns: 10
        connectTimeout: "10s"
        timeout: "1s"
        consistency: "LOCAL_QUORUM"
        serialConsistency: "LOCAL_SERIAL"
        hostSelectionPolicy: "tokenaware,roundrobin"
      
    # Visibility datastore
    visibility:
      nosql:
        pluginName: "cassandra"
        hosts: "cassandra-service.cadence.svc.cluster.local"
        keyspace: "cadence_visibility"
        user: "cassandra"
        password: {{ .Env.CASSANDRA_PASSWORD }}
        protoVersion: 4
        maxConns: 10
        connectTimeout: "10s"
        timeout: "1s"
        consistency: "LOCAL_QUORUM"
        serialConsistency: "LOCAL_SERIAL"
        hostSelectionPolicy: "tokenaware,roundrobin"
      

# Ringpop configuration
ringpop:
  name: cadence
  bootstrapMode: dns
  bootstrapHosts:
    - cadence-frontend-headless:7933
    - cadence-history-headless:7934
    - cadence-matching-headless:7935
    - cadence-worker-headless:7939
  maxJoinDuration: 30s

# Cluster configuration
clusterGroupMetadata:
  failoverVersionIncrement: 10
  primaryClusterName: cluster0
  currentClusterName: cluster0
  clusterGroup:
    cluster0:
      enabled: true
      initialFailoverVersion: 0
      rpcAddress: cadence-frontend:7833
      rpcTransport: "grpc"
  clusterRedirectionPolicy:
    policy: noop

# Services configuration
services:
  frontend:
    rpc:
      port: 7933
      grpcPort: 7833
      bindOnIP: {{ default .Env.POD_IP "0.0.0.0" }}
      grpcMaxMsgSize: 4194304
    metrics:
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"

  history:
    rpc:
      port: 7934
      grpcPort: 7834
      bindOnIP: {{ default .Env.POD_IP "0.0.0.0" }}
      grpcMaxMsgSize: 4194304
    metrics:
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"

  matching:
    rpc:
      port: 7935
      grpcPort: 7835
      bindOnIP: {{ default .Env.POD_IP "0.0.0.0" }}
      grpcMaxMsgSize: 4194304
    metrics:
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"

  worker:
    rpc:
      port: 7939
      bindOnIP: {{ default .Env.POD_IP "0.0.0.0" }}
      grpcMaxMsgSize: 4194304
    metrics:
      prometheus:
        timerType: histogram
        listenAddress: "0.0.0.0:9090"



# Archival configuration
archival:
  history:
    status: "disabled"
    enableRead: false
    provider:
      filestore:
        fileMode: "0644"
        dirMode: "0755"
  visibility:
    status: "disabled"
    enableRead: false
    provider:
      filestore:
        fileMode: "0644"
        dirMode: "0755"

# Domain defaults configuration
domainDefaults:
  archival:
    history:
      status: "disabled"
    visibility:
      status: "disabled"

# Blobstore configuration
blobstore:
  filestore:
    outputDirectory: "/etc/cadence/blobstore"

# Public client configuration
publicClient:
  transport: "grpc"
  RefreshInterval: "10s"

# Dynamic configuration
dynamicconfig:
  client: "filebased"
  filebased:
    filepath: "/etc/cadence/config/dynamicconfig/config.yaml"
    pollInterval: "60s"
```

### Dynamic Configs
```yaml
system.minRetentionDays:
- constraints: {}
  value: 0
system.readVisibilityStoreName:
- value: db
system.writeVisibilityStoreName:
- value: db
```

**Note**: Using default configuration.

## Environment Variables

I only have the following environment variables configured:
- `SERVICES`
- Cassandra password

## Error Log

```
[Fx] RUNNING
{"level":"info","ts":"2025-06-24T15:37:01.311Z","msg":"frontend starting","service":"cadence-frontend","logging-call-at":"service.go:130"}
{"level":"info","ts":"2025-06-24T15:37:01.312Z","msg":"LRU cache initialized","service":"cadence-frontend","value":"map[isSizeBased:false maxCount:100 maxSize:1073741824]","logging-call-at":"lru.go:204"}
{"level":"info","ts":"2025-06-24T15:37:01.313Z","msg":"RuntimeMetricsReporter started","service":"cadence-frontend","logging-call-at":"runtime.go:172"}
{"level":"info","ts":"2025-06-24T15:37:01.313Z","msg":"PProf not started due to port not set","service":"cadence-frontend","logging-call-at":"pprof.go:65"}
{"level":"info","ts":"2025-06-24T15:37:01.313Z","msg":"direct peer chooser started","service":"cadence-frontend","dest-service":"cadence-history","logging-call-at":"direct_peer_chooser.go:96"}
{"level":"info","ts":"2025-06-24T15:37:01.314Z","msg":"direct peer chooser started","service":"cadence-frontend","dest-service":"cadence-matching","logging-call-at":"direct_peer_chooser.go:96"}
{"level":"info","ts":"2025-06-24T15:37:01.316Z","msg":"Starting membership resolver","service":"cadence-frontend","component":"membership-resolver","component":"membership-resolver","logging-call-at":"resolver.go:124"}
{"level":"warn","ts":"2025-06-24T15:37:04.323Z","msg":"error in prometheus reporter","service":"cadence-frontend","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"cadence_authorization_latency\", help: \"cadence_authorization_latency histogram\", constLabels: {}, variableLabels: [cadence_service operation domain]} has different label names or a different help string","logging-call-at":"metrics.go:151"}
{"level":"warn","ts":"2025-06-24T15:37:04.324Z","msg":"error in prometheus reporter","service":"cadence-frontend","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"cadence_authorization_latency\", help: \"cadence_authorization_latency histogram\", constLabels: {}, variableLabels: [cadence_service operation domain]} has different label names or a different help string","logging-call-at":"metrics.go:151"}
{"level":"warn","ts":"2025-06-24T15:37:04.324Z","msg":"error in prometheus reporter","service":"cadence-frontend","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"cadence_requests\", help: \"cadence_requests counter\", constLabels: {}, variableLabels: [cadence_service operation]} has different label names or a different help string","logging-call-at":"metrics.go:151"}
{"level":"warn","ts":"2025-06-24T15:37:04.324Z","msg":"error in prometheus reporter","service":"cadence-frontend","error":"a previously registered descriptor with the same fully-qualified name as Desc{fqName: \"cadence_latency\", help: \"cadence_latency histogram\", constLabels: {}, variableLabels: [cadence_service operation]} has different label names or a different help string","logging-call-at":"metrics.go:151"}
```

## Expected Behavior

Cadence components should run without continuous Prometheus metrics errors.

## Actual Behavior

Continuous errors related to Prometheus metrics appear in all Cadence components.

## Environment Details

- **Cadence server version**: 1.3.1
- **Kubernetes cluster**: 1.32

## Related Links

- Upstream fix: https://github.com/cadence-workflow/cadence/pull/6963
