### ISSUE TITLE
Align helm chart with best practises

### ISSUE THREAD

**Issue by samuel-lindgren** [cadence-workflow/cadence-charts#8]
The Helm Chart currently does not incorporate several recommended best practices such as:

* `securityContext`: to allow containers run as non-root and follow principle of least privilege
* `affinity` for controlling pod placement.
* `tolerations`: for scheduling pods to tolerate specific conditions.
*  use `gRPC` where possible:  prefer to use `gRPC` over `TChannel`(`RPC`) due to it being more standardized. 

**Inspiration**
Banzai:
* [securityContext](https://github.com/search?q=repo%3Abanzaicloud%2Fbanzai-charts+path%3A%2F%5Ecadence%5C%2F%2F+securityContext&type=code)
* [tolerations](https://github.com/search?q=repo%3Abanzaicloud%2Fbanzai-charts+path%3A%2F%5Ecadence%5C%2F%2F+tolerations&type=code)
* [affinity](https://github.com/search?q=repo%3Abanzaicloud%2Fbanzai-charts+path%3A%2F%5Ecadence%5C%2F%2F+affinity&type=code)

Temporal:
* [securityContext](https://github.com/search?q=repo%3Atemporalio%2Fhelm-charts+path%3A%2F%5Echarts%5C%2Ftemporal%5C%2F%2F+securityContext&type=code)
* [tolerations](https://github.com/search?q=repo%3Atemporalio%2Fhelm-charts+path%3A%2F%5Echarts%5C%2Ftemporal%5C%2F%2F+tolerations&type=code)
* [affinity](https://github.com/search?q=repo%3Atemporalio%2Fhelm-charts+path%3A%2F%5Echarts%5C%2Ftemporal%5C%2F%2F+affinity&type=code)

 gRPC: 
* One approach could be to use grpc-rpc like Temporal's [server-service.yaml](https://raw.githubusercontent.com/temporalio/helm-charts/refs/heads/main/charts/temporal/templates/server-service.yaml)
* Another approach could be to use grpc strictly where possible as shown in below code (from our fork):

``` yaml
{{- range $service := (list "frontend" "matching" "history" "worker") }}
{{- $serviceValues := index $.Values.server $service -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cadence.componentname" (list $ (printf "%s-headless" $service)) }}
  labels: # labels
  annotations: #annotations
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ $serviceValues.service.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    {{- /*
       All services but the worker have a gRPC port.
    */ -}}
    {{- if (ne $service "worker") }}
    - port: {{ $serviceValues.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end }}
    {{- if $.Values.metricsEnabled }}
    - name: metrics
      port: {{ $.Values.services.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "cadence.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $service }}

---
{{- end }} 
```
